### ISSUE TITLE
Feature: Use webpack to build repo

### ISSUE THREAD

**Issue by aymanapatel** [aquadzn/learn-x-by-doing-y#11]
Can we refactor to use webpack for building static files?

Useful link to do that https://github.com/ivarprudnikov/webpack-static-html-pages/

This can help in using environment variables for the `main.js` which is currently exposed, which is not good security practice (even though it is for testing purpose)

**Comment by aquadzn** [comment]
* thanks but I don't want to use npm
* even if the key is hidden from code it will still be accessible client-side
* Search-only key can be exposed: https://www.algolia.com/doc/guides/security/api-keys/#search-only-api-key

**Comment by aquadzn** [comment]
e.g. https://my-notes-algolia.aymanapatel.vercel.app/
![image](https://user-images.githubusercontent.com/46140458/104840138-d5944e00-58c5-11eb-820f-e21015df2674.png)

**Comment by aymanapatel** [comment]
I have added `API_SECRET` as an environment variable. Not totally secure as network intercepts it. Is there a way to obfuscate `API_SECRET`?

**Comment by aquadzn** [comment]
not really without server-side it would still be intercepted
